# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: olympics.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'olympics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eolympics.proto\x12\x08olympics\"d\n\x07\x41thlete\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\r\n\x05sport\x18\x04 \x01(\t\x12\x1f\n\x06medals\x18\x05 \x03(\x0b\x32\x0f.olympics.Medal\"|\n\x05Medal\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.olympics.Medal.MedalType\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\"-\n\tMedalType\x12\x08\n\x04GOLD\x10\x00\x12\n\n\x06SILVER\x10\x01\x12\n\n\x06\x42RONZE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'olympics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATHLETE']._serialized_start=28
  _globals['_ATHLETE']._serialized_end=128
  _globals['_MEDAL']._serialized_start=130
  _globals['_MEDAL']._serialized_end=254
  _globals['_MEDAL_MEDALTYPE']._serialized_start=209
  _globals['_MEDAL_MEDALTYPE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
